# Generated by Django 4.2.4 on 2023-08-09 12:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Batch', models.CharField(max_length=200)),
                ('Batch_list', models.TextField(blank=True, null=True)),
                ('Created_Date_Time', models.DateField(auto_now_add=True)),
                ('Modified_Date_Time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(max_length=200)),
                ('Created_Date_Time', models.DateField(auto_now_add=True)),
                ('Modified_Date_Time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mail_Tempalte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Subject', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, null=True)),
                ('Created_Date_Time', models.DateField(auto_now_add=True)),
                ('Modified_Date_Time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pofile_Id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('Pofile_Name', models.CharField(max_length=200)),
                ('Pofile_dsc', models.CharField(max_length=400)),
                ('Pofile_Email', models.CharField(max_length=400)),
                ('Pofile_Point', models.IntegerField(default=0, null=True)),
                ('Pofile_Pic', models.ImageField(upload_to='uploads/')),
                ('Pofile_flag', models.BooleanField(default=False)),
                ('Pofile_competitor', models.BooleanField(default=False)),
                ('Pofile_Created_Date_Time', models.DateField(auto_now_add=True)),
                ('Pofile_Modified_Date_Time', models.DateField(auto_now=True)),
                ('Pofile_Gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dasboardApp.gender_table')),
            ],
        ),
        migrations.CreateModel(
            name='SendInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SendInvite_Id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('SendInvite_link', models.CharField(max_length=200)),
                ('SendInvite_Active', models.BooleanField(default=False)),
                ('SendInvite_Created_Date_Time', models.DateField(auto_now_add=True)),
                ('SendInvite_Modified_Date_Time', models.DateField(auto_now=True)),
                ('SendInvite_Batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dasboardApp.batchinvite')),
                ('SendInvite_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dasboardApp.pofile')),
            ],
        ),
        migrations.AddField(
            model_name='batchinvite',
            name='Batch_Template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dasboardApp.mail_tempalte'),
        ),
    ]
