# Generated by Django 4.2.4 on 2023-08-10 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dasboardApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchinvite',
            name='Batch_Send',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sendinvite',
            name='SendInvite_Batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dasboardApp.batchinvite'),
        ),
    ]
